targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/graphql_api.dart
              naming_scheme: pathedWithFields
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/**/*.graphql
